-- Add translation_status column to dynamic collection tables
-- Run this script for each of your collection tables

-- Example for a blog table:
-- ALTER TABLE blog 
-- ADD COLUMN IF NOT EXISTS translation_status VARCHAR(50) DEFAULT 'draft';

-- Example for a news table:
-- ALTER TABLE news 
-- ADD COLUMN IF NOT EXISTS translation_status VARCHAR(50) DEFAULT 'draft';

-- Example for a product table:
-- ALTER TABLE product 
-- ADD COLUMN IF NOT EXISTS translation_status VARCHAR(50) DEFAULT 'draft';

-- Possible values:
-- 'draft' - Initial state
-- 'ai_generated' - Generated by AI, needs review
-- 'reviewed' - Reviewed by human
-- 'published' - Published and live

-- To apply to all your collection tables, replace 'your_table_name' with actual table names:
-- ALTER TABLE your_table_name 
-- ADD COLUMN IF NOT EXISTS translation_status VARCHAR(50) DEFAULT 'draft';
